# Site settings
title: Lbbxsxlz 半路出家的攻城狮
email: Lbbxsxlz@gmail.com
description: Lbbxsxlz's Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: lbbxsxlz
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/lbbxsxlz/lbbxsxlz.github.io/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/lbbxsxlz/lbbxsxlz.github.io/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lbbxsxlz.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
#disqus_shortname: lixizhi
#disqus_url: "http://lbbxsxlz.github.io"
#########################################
#intensedebate_comments: true

#gitment
comment_gitment_repo: lbbxsxlz.github.io
comment_gitment_clientId: 3862a968d2e156809eae
comment_gitment_clientSecret: ddd9033f2211fe05b59ae4fe7c4d561f8ccccbfb

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 5307f381c6753dc374226f13e184df87
google_analytics_id: UA-169391398-1 # google 分析追踪id

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
